FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    strace \
    tcpdump \
    tshark \
    procps \
    coreutils \
    bash \
    file \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /sandbox/output /tmp /var/tmp /dev/shm /root/.ssh

COPY upx /usr/bin/upx
RUN chmod +x /usr/bin/upx
COPY sandbox-entrypoint.sh /sandbox/entrypoint.sh
RUN chmod +x /sandbox/entrypoint.sh

ENTRYPOINT ["/sandbox/entrypoint.sh"]
